- name: Setup docker
  ansible.builtin.include_tasks: docker.yaml
- name: Setup openvswitch
  ansible.builtin.include_tasks: openvswitch.yaml
- name: Create user
  ansible.builtin.user:
    name: participant
    shell: /bin/bash
- name: Setup command
  become: true
  ansible.builtin.template:
    src: .commands.j2.sh
    dest: /etc/.command
    mode: "0644"
- name: Setup bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: "source /etc/.command"
    create: yes
    state: present
