version: "3"

tasks: 
  init: 
    cmds: 
      - npm install 
      - npm install --global cdktf-cli@latest
  plan:
    deps: 
      - synth
    cmds:
      - cdktf plan
  deploy:
    deps: 
      - synth
    cmds:
      - cdktf deploy
  synth: 
    cmds: 
      - cdktf synth