FROM ubuntu/bind9:latest

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    isc-dhcp-client \
    nano \
    iproute2 \
    net-tools \
    iputils-ping \
    netplan.io 
